### ISSUE TITLE
天气状况可以翻译吗？

### ISSUE THREAD

**Issue by twilightsay** [HK417KEN/Lethal_Company_Simplified_Chinese_Terminal_Localization#1]
我阅读了cfg，发现天气状况是由 `[planetTime]` 这个变量来控制的。所以有办法来翻译变量内的东西吗？

**Comment by HK417KEN** [comment]
目前不行，NewTerminal 对翻译这种用途来说还是不太够的。

**Comment by twilightsay** [comment]
那您以后有考虑使用别的方法来翻译吗？之前下载的一个终端汉化使用了dll的形式，但这种

**Comment by twilightsay** [comment]
好的，谢谢~
但如果可能的话，您有考虑别的办法进行终端翻译吗？例如我之前有看到一个终端汉化使用了dll写死，不过这对于新加MOD后修改简直是灾难==

**Comment by HK417KEN** [comment]
> 好的，谢谢~ 但如果可能的话，您有考虑别的办法进行终端翻译吗？例如我之前有看到一个终端汉化使用了dll写死，不过这对于新加MOD后修改简直是灾难==

抱歉哈，我现在没有这个能力去做更深层次的翻译，只能按着现有mod放出来的简单的东西修修改改什么的。

**Comment by HK417KEN** [comment]
本项目已经弃用了，感谢支持，请使用其他汉化Mod代替，谢谢！

建议使用这个汉化Mod：
- [Lethal Company Simplified Chinese Localization](https://thunderstore.io/c/lethal-company/p/SweetFox/Lethal_Company_Simplified_Chinese_Localization/) by  [SweetFox](https://thunderstore.io/c/lethal-company/p/SweetFox/)

这个 Mod 可以翻译天气状态了。
